<?php
require_once("../config/database.php");
require("../fpdf/fpdf.php");

date_default_timezone_set('Asia/Kolkata');
// Validate request
if (!isset($_GET['hall_ticket']) || !isset($_GET['semester_id'])) {
    die("Invalid Request");
}

$hall_ticket = trim($_GET['hall_ticket']);
$semester_id = intval($_GET['semester_id']);
$studentStmt = $conn->prepare("
    SELECT *
    FROM students
    WHERE hall_ticket = ?
");

$studentStmt->bind_param("s", $hall_ticket);
$studentStmt->execute();

$studentResult = $studentStmt->get_result();

if ($studentResult->num_rows == 0) {
    die("Student not found.");
}

$student = $studentResult->fetch_assoc();
$semesterStmt = $conn->prepare("
    SELECT semester_name, academic_year
    FROM semesters
    WHERE semester_id = ?
");

$semesterStmt->bind_param("i", $semester_id);
$semesterStmt->execute();

$semester = $semesterStmt->get_result()->fetch_assoc();
$pdf = new FPDF();

$pdf->AddPage();

// Header
$pdf->SetFillColor(13,110,253);
$pdf->SetTextColor(255,255,255);

$pdf->SetFont('Arial','B',20);
$pdf->Cell(0,15,'EDUNOTIFY',0,1,'C',true);

$pdf->SetFont('Arial','',13);
$pdf->Cell(0,10,'ABC Institute of Technology',0,1,'C',true);

// Reset text color
$pdf->SetTextColor(0,0,0);

$pdf->Ln(5);

$pdf->SetFillColor(230,240,255);

$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,10,'Student Details',1,1,'L',true);

$pdf->SetFont('Arial','',11);

$pdf->Cell(50,8,'Hall Ticket');
$pdf->Cell(0,8,$student['hall_ticket'],0,1);

$pdf->Cell(50,8,'Student Name');
$pdf->Cell(0,8,$student['full_name'],0,1);

$pdf->Cell(50,8,'Department');
$pdf->Cell(0,8,$student['department'],0,1);

$pdf->Cell(50,8,'Year');
$pdf->Cell(0,8,$student['year'],0,1);

$pdf->Cell(50,8,'Semester');
$pdf->Cell(0,8,$semester['semester_name'],0,1);

$pdf->Cell(50,8,'Academic Year');
$pdf->Cell(0,8,$semester['academic_year'],0,1);

$resultStmt = $conn->prepare("
SELECT
    subjects.subject_code,
    subjects.subject_name,
    subjects.credits,
    results.marks,
    results.grade,
    results.status
FROM results
INNER JOIN subjects
ON subjects.subject_id = results.subject_id
WHERE results.student_id = ?
AND results.semester_id = ?
ORDER BY subjects.subject_code
");

$resultStmt->bind_param(
    "ii",
    $student['student_id'],
    $semester_id
);

$resultStmt->execute();

$resultData = $resultStmt->get_result();

$totalMarks = 0;
$totalSubjects = 0;
$overallStatus = "PASS";

$pdf->Ln(10);

$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'Subject-wise Results',0,1);

$pdf->SetFillColor(13,110,253);
$pdf->SetTextColor(255,255,255);

$pdf->SetFont('Arial','B',10);

$pdf->Cell(25,8,'Code',1,0,'C',true);
$pdf->Cell(65,8,'Subject',1,0,'C',true);
$pdf->Cell(20,8,'Credit',1,0,'C',true);
$pdf->Cell(20,8,'Marks',1,0,'C',true);
$pdf->Cell(20,8,'Grade',1,0,'C',true);
$pdf->Cell(40,8,'Status',1,1,'C',true);

$pdf->SetTextColor(0,0,0);

$pdf->Ln();

$pdf->SetFont('Arial','',10);

while($row = $resultData->fetch_assoc())
{
    $totalMarks += $row['marks'];
    $totalSubjects++;

    if(strtoupper($row['status']) != "PASS")
    {
        $overallStatus = "FAIL";
    }

    $pdf->Cell(25,8,$row['subject_code'],1);
    $pdf->Cell(65,8,$row['subject_name'],1);
    $pdf->Cell(20,8,$row['credits'],1);
    $pdf->Cell(20,8,$row['marks'],1);
    $pdf->Cell(20,8,$row['grade'],1);
    $pdf->Cell(40,8,$row['status'],1);

    $pdf->Ln();
}

$percentage = ($totalSubjects > 0)
    ? ($totalMarks / ($totalSubjects * 100)) * 100
    : 0;

if ($percentage >= 90)
    $overallGrade = "A+";
elseif ($percentage >= 80)
    $overallGrade = "A";
elseif ($percentage >= 70)
    $overallGrade = "B";
elseif ($percentage >= 60)
    $overallGrade = "C";
elseif ($percentage >= 50)
    $overallGrade = "D";
elseif ($percentage >= 35)
    $overallGrade = "E";
else
    $overallGrade = "F";

$pdf->Ln(10);

$pdf->SetFillColor(220,255,220);

$pdf->SetFont('Arial','B',13);

$pdf->Cell(
    0,
    10,
    'Result Summary',
    1,
    1,
    'L',
    true
);

$pdf->SetFont('Arial','',12);

$pdf->Cell(60,8,'Total Subjects');
$pdf->Cell(0,8,$totalSubjects,0,1);

$pdf->Cell(60,8,'Total Marks');
$pdf->Cell(0,8,$totalMarks,0,1);

$pdf->Cell(60,8,'Percentage');
$pdf->Cell(0,8,number_format($percentage,2).'%',0,1);

$pdf->Cell(60,8,'Overall Grade');
$pdf->Cell(0,8,$overallGrade,0,1);

$pdf->Cell(60,8,'Overall Result');
$pdf->Cell(0,8,$overallStatus,0,1);

$pdf->Ln(15);

$pdf->SetX(125);
$pdf->Cell(60,8,'__________________',0,1,'C');

$pdf->SetX(125);
$pdf->Cell(60,8,'Controller of Examinations',0,1,'C');

$pdf->Ln(10);

$pdf->SetFont('Arial','I',10);

$pdf->Cell(
    0,
    8,
    'Generated on: '.date('d M Y, h:i A'),
    0,
    1,
    'R'
);

$pdf->Cell(
    0,
    8,
    'Generated by EduNotify',
    0,
    1,
    'C'
);

$pdf->Output();